//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public decimal ID_EMPLOYEE { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string PATRONYMIC { get; set; }
        public System.DateTime BIRTHDATE { get; set; }
        public decimal SALARY { get; set; }
        public string POSITION { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public string ISADMIN { get; set; }
    }
}
