//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICES
    {
        public decimal ID_SERVIS { get; set; }
        public decimal ID_COUNTRY { get; set; }
        public string VISA_SERVICE { get; set; }
        public string RESIDENCE { get; set; }
        public string NUTRITION { get; set; }
        public string EXCURSIONS { get; set; }
    }
}
