//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOURS
    {
        public decimal ID_TOURS { get; set; }
        public decimal ID_SERVIS { get; set; }
        public decimal ID_TRANSPORT { get; set; }
        public System.DateTime DISPATCH_DATE { get; set; }
        public System.DateTime ARRIVAL_DATE { get; set; }
        public decimal TOUR_PRICE { get; set; }
        public decimal STAY_LENGTH { get; set; }
        public decimal PERSON_NUMBER { get; set; }
    }
}
