//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WedInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        public decimal ID_CLIENT { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string PATRONYMIC { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
    }
}
