//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WedInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        public decimal ID_ORDER { get; set; }
        public decimal ID_TOUR { get; set; }
        public decimal ID_EMPLOYEE { get; set; }
        public decimal ID_CLIENT { get; set; }
        public System.DateTime REGISTRATION_DATE { get; set; }
        public Nullable<decimal> SALE_PRICE { get; set; }
    }
}
